from . import student
from . import attendance
from . import fee
from . import classs
from . import result
from . import school_subject
from . import bank
from . import exam
from . import teacher
from . import timetable
from . import salary
from . import salary_settings
from . import staff_attendance
from . import staff_head
from . import result_wizard
from . import attendance_wizard
from . import attendance_settings
from . import attendance_message_queue
from . import qr_scanner_wizard
from . import library_book
from . import library_issue
from . import student_class_history